<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body style="margin-left: 30%; background-color:lavenderblush;">


<?php

foreach($forecast as $k => $v)
{
    if($k == 'location'){
        $place = $v['name'];
    
    }
    if($k == 'forecast')
    {
        foreach($v as $k1 => $v1)
        {             
                foreach($v1[0] as $k2 => $v2)
                {
                    if($k2 == 'day')
                        {
                            $maxtemp = $v2['maxtemp_c'];
                            $avgtemp = $v2['avgtemp_c'];
                            $mintemp = $v2['mintemp_f'];
                            $weather = '';
                          

                        }
                    if($k2 == 'hour')
                    {   
                        foreach($v2 as $k3 => $v3)
                        {
                            ?>
                    <h4><b>Place Name: </b><?php print_r($place); ?></h4>
                    <p>Date and time : <?php print_r($v3['time']);?></p>
                    <p>Temp in celsius : <?php print_r($v3['temp_c']);?></p>
                    <p>Wind in kph : <?php print_r($v3['wind_kph']);?></p>
                    <p>Chance of Rain : <?php if($v3['chance_of_rain'] == 0){ print_r("No");}else{print_r("Yes");}?></p>
                    <p>Weather : <?php print_r($v3['condition']['text']);?></p>

                    <p>maxtemp : <?php print_r($maxtemp);?></p>
                    <p>avgtemp : <?php print_r($avgtemp);?></p>
                    <p>mintemp : <?php print_r($mintemp);?></p>
                    <br><br>

    <?php } print_r($v2['avgtemp_c']);?>
<?php } } }}}?>
</body>
</html>

    


